Feature/sc 20289/competency client help repo
Cyber4All/competency-constructor-help pull request #1
Opened 2023-03-28 17:35 UTC by shanioffe

Creates the competency-constructor-help repo and initializes it with 6 help pages for the user

2023-03-29 12:45 UTC, JosueMolinaMorales requested changes
Just some small changes. Do you know if this is supposed to be a jekyll webpage? Like the cyber4all docs and competency-docs?

2023-03-29 12:45 UTC, JosueMolinaMorales commented on editCompetency.md
> +<<<<<<< HEAD
These head and tails (line 21) can be deleted.

2023-03-29 12:45 UTC, JosueMolinaMorales commented on resetPassword.md
> +<<<<<<< HEAD
here too

2023-03-29 12:45 UTC, JosueMolinaMorales commented on submitCompetency.md
> +<<<<<<< HEAD
and here

2023-03-29 12:57 UTC, mfranz1 reviewed
Just Josue's comments

2023-03-29 14:29 UTC, Cwagne17 reviewed
Once Sway's comments are addressed this is good

2023-03-29 17:46 UTC, Maliyaa approved these changes

2023-03-30 15:05 UTC, pmanal1 reviewed
Looks good. One note: I noticed in the repo that we have duplicate `createCompetency.md` and `searchCompetency.md` files. You should probably delete one of each.

2023-03-31 13:19 UTC, mfranz1 commented on editCompetency.md
> +>>>>>>> 4ee7da073bd147ad797fe3e9bf64d6a2598bc09c
```suggestion

```

2023-03-31 13:20 UTC, mfranz1 commented on editCompetency.md
> +<<<<<<< HEAD
```suggestion
```

2023-03-31 13:20 UTC, mfranz1 commented on resetPassword.md
> +<<<<<<< HEAD
```suggestion
```

2023-03-31 14:16 UTC, JosueMolinaMorales requested changes
The previous changes havent been addressed and you will need to install Jekyll to properly setup the repo. Here is the homepage to Jekyll https://jekyllrb.com/
you should look into the installation guide and creating the project. You should see a _config.yml file after and the structure should resemble that of cyber4all docs and competency docs. let me know if you have any questions.

2023-04-03 14:16 UTC, Cwagne17 reviewed
Once Josue's and Mike's comments are addressed rerequest.

2023-04-05 16:09 UTC, pzalep1 reviewed
Once Josue's and Mike's comments are addressed you will be good!

2023-04-21 17:12 UTC, closed without merging